### ISSUE TITLE
Unable to connect api via basic auth

### ISSUE THREAD

**Issue by williamespindola** [mautic/api-library#143]
I'm using mautic via docker with this docker-composer file:

```
mautic:
  image: mautic/mautic
  links:
    - mauticdb:mysql
  ports:
    - 8080:80

mauticdb:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: example
```

With this request:
```
curl -X GET \
  http://localhost:8080/api \
  -H 'Authorization: Basic YWRtaW46YWRtaW4xMjM=' \
  -H 'Cache-Control: no-cache' \
  -H 'Postman-Token: 5e8f4ac9-6b92-476b-da01-b2f2646a1ccd'
```

I have this error:
```
{
    "errors": [
        {
            "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator!",
            "code": 404,
            "type": null
        }
    ],
    "error": {
        "message": "Looks like I encountered an error (error #404). If I do it again, please report me to the system administrator! (`error` is deprecated as of 2.6.0 and will be removed in 3.0. Use the `errors` array instead.)",
        "code": 404
    }
}
```

The api and http basic is enable on Configuration -> API Settings.
I'm using the same login and password created on mautic set up: username: admin and password: admin123
